/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PostRouteImport } from './routes/post'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobsJobIdProposalRouteImport } from './routes/jobs.$jobId.proposal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdProposalRoute = JobsJobIdProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => JobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/proposal': typeof JobsJobIdProposalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs': typeof JobsIndexRoute
  '/jobs/$jobId/proposal': typeof JobsJobIdProposalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/proposal': typeof JobsJobIdProposalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kyc'
    | '/login'
    | '/messages'
    | '/post'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/jobs/$jobId/proposal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kyc'
    | '/login'
    | '/messages'
    | '/post'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/jobs/$jobId'
    | '/jobs'
    | '/jobs/$jobId/proposal'
  id:
    | '__root__'
    | '/'
    | '/kyc'
    | '/login'
    | '/messages'
    | '/post'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/jobs/$jobId/proposal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/proposal': {
      id: '/jobs/$jobId/proposal'
      path: '/proposal'
      fullPath: '/jobs/$jobId/proposal'
      preLoaderRoute: typeof JobsJobIdProposalRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdProposalRoute: typeof JobsJobIdProposalRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdProposalRoute: JobsJobIdProposalRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
