/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PostRouteImport } from './routes/post'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesNotificationsRouteImport } from './routes/messages.notifications'
import { Route as MessagesSupportRouteImport } from './routes/messages.support'
import { Route as JobsJobIdProposalRouteImport } from './routes/jobs.$jobId.proposal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesNotificationsRoute = MessagesNotificationsRouteImport.update({
  id: '/messages/notifications',
  path: '/messages/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesSupportRoute = MessagesSupportRouteImport.update({
  id: '/messages/support',
  path: '/messages/support',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdProposalRoute = JobsJobIdProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => JobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/messages/notifications': typeof MessagesNotificationsRoute
  '/messages/support': typeof MessagesSupportRoute
  '/jobs/': typeof JobsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/jobs/$jobId/proposal': typeof JobsJobIdProposalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/messages/notifications': typeof MessagesNotificationsRoute
  '/messages/support': typeof MessagesSupportRoute
  '/jobs': typeof JobsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/jobs/$jobId/proposal': typeof JobsJobIdProposalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/messages/notifications': typeof MessagesNotificationsRoute
  '/messages/support': typeof MessagesSupportRoute
  '/jobs/': typeof JobsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/jobs/$jobId/proposal': typeof JobsJobIdProposalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/business'
    | '/kyc'
    | '/login'
    | '/post'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/jobs/$jobId'
    | '/messages/notifications'
    | '/messages/support'
    | '/jobs/'
    | '/messages/'
    | '/jobs/$jobId/proposal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/business'
    | '/kyc'
    | '/login'
    | '/post'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/jobs/$jobId'
    | '/messages/notifications'
    | '/messages/support'
    | '/jobs'
    | '/messages'
    | '/jobs/$jobId/proposal'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/business'
    | '/kyc'
    | '/login'
    | '/post'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/jobs/$jobId'
    | '/messages/notifications'
    | '/messages/support'
    | '/jobs/'
    | '/messages/'
    | '/jobs/$jobId/proposal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  BusinessRoute: typeof BusinessRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  MessagesNotificationsRoute: typeof MessagesNotificationsRoute
  MessagesSupportRoute: typeof MessagesSupportRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/notifications': {
      id: '/messages/notifications'
      path: '/messages/notifications'
      fullPath: '/messages/notifications'
      preLoaderRoute: typeof MessagesNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/support': {
      id: '/messages/support'
      path: '/messages/support'
      fullPath: '/messages/support'
      preLoaderRoute: typeof MessagesSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/proposal': {
      id: '/jobs/$jobId/proposal'
      path: '/proposal'
      fullPath: '/jobs/$jobId/proposal'
      preLoaderRoute: typeof JobsJobIdProposalRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdProposalRoute: typeof JobsJobIdProposalRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdProposalRoute: JobsJobIdProposalRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  BusinessRoute: BusinessRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  MessagesNotificationsRoute: MessagesNotificationsRoute,
  MessagesSupportRoute: MessagesSupportRoute,
  JobsIndexRoute: JobsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
